<?php
namespace configdata;
/**
* gen by zeus.php
*/
class configdata_mission_completecondition_setting {
const k_id = "id";
const k_conditiontype = "conditiontype";
const k_conditionoperatetype = "conditionoperatetype";
private static $_data = NULL;
public static function data() {
if (is_null ( self::$_data )) {
self::$_data = [
['id'=>'1','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'2','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'3','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'4','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'5','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'6','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'7','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'8','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'9','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'10','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'11','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'12','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'13','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'14','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'15','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'16','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'17','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'18','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'19','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'20','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'21','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'22','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'23','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'24','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'25','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'26','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'27','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'28','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'29','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'30','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'31','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'32','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'33','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'34','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'35','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'36','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'37','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'38','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'39','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'40','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'41','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'42','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'43','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'44','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'45','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'46','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'47','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'48','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'49','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'50','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'51','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'52','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'53','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'54','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'55','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'56','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'57','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'58','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'59','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'60','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'61','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'62','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'63','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'64','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'65','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'66','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'67','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'68','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'69','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'70','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'71','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'72','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'73','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'74','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'75','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'76','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'77','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'78','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'79','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'80','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'81','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'82','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'83','conditiontype'=>'1','conditionoperatetype'=>'set'],
['id'=>'84','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'85','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'86','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'87','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'88','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'89','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'90','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'91','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'92','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'93','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'94','conditiontype'=>'1','conditionoperatetype'=>'inc'],
['id'=>'95','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'96','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'97','conditiontype'=>'2','conditionoperatetype'=>'inc'],
['id'=>'98','conditiontype'=>'2','conditionoperatetype'=>'set'],
['id'=>'99','conditiontype'=>'1','conditionoperatetype'=>'inc']
];
}
 return self::$_data;
}
}
