<?php
namespace configdata;
/**
* gen by zeus.php
*/
class configdata_restaurant_popularity_level_setting {
const k_level = "level";
const k_stagelevel = "stagelevel";
const k_popularityminvalue = "popularityminvalue";
const k_popularitymaxvalue = "popularitymaxvalue";
const k_customflow = "customflow";
private static $_data = NULL;
public static function data() {
if (is_null ( self::$_data )) {
self::$_data = [
['level'=>'1','stagelevel'=>'0','popularityminvalue'=>'0','popularitymaxvalue'=>'25','customflow'=>'3'],
['level'=>'2','stagelevel'=>'1','popularityminvalue'=>'25','popularitymaxvalue'=>'50','customflow'=>'3'],
['level'=>'3','stagelevel'=>'1','popularityminvalue'=>'50','popularitymaxvalue'=>'75','customflow'=>'3'],
['level'=>'4','stagelevel'=>'1','popularityminvalue'=>'75','popularitymaxvalue'=>'100','customflow'=>'3'],
['level'=>'5','stagelevel'=>'1','popularityminvalue'=>'100','popularitymaxvalue'=>'125','customflow'=>'3'],
['level'=>'6','stagelevel'=>'1','popularityminvalue'=>'125','popularitymaxvalue'=>'150','customflow'=>'3'],
['level'=>'7','stagelevel'=>'1','popularityminvalue'=>'150','popularitymaxvalue'=>'175','customflow'=>'3'],
['level'=>'8','stagelevel'=>'1','popularityminvalue'=>'175','popularitymaxvalue'=>'200','customflow'=>'3'],
['level'=>'9','stagelevel'=>'1','popularityminvalue'=>'200','popularitymaxvalue'=>'225','customflow'=>'3'],
['level'=>'10','stagelevel'=>'2','popularityminvalue'=>'225','popularitymaxvalue'=>'250','customflow'=>'3'],
['level'=>'11','stagelevel'=>'2','popularityminvalue'=>'250','popularitymaxvalue'=>'275','customflow'=>'3'],
['level'=>'12','stagelevel'=>'2','popularityminvalue'=>'275','popularitymaxvalue'=>'300','customflow'=>'3'],
['level'=>'13','stagelevel'=>'2','popularityminvalue'=>'300','popularitymaxvalue'=>'325','customflow'=>'3'],
['level'=>'14','stagelevel'=>'2','popularityminvalue'=>'325','popularitymaxvalue'=>'350','customflow'=>'3'],
['level'=>'15','stagelevel'=>'2','popularityminvalue'=>'350','popularitymaxvalue'=>'375','customflow'=>'3'],
['level'=>'16','stagelevel'=>'2','popularityminvalue'=>'375','popularitymaxvalue'=>'400','customflow'=>'3'],
['level'=>'17','stagelevel'=>'2','popularityminvalue'=>'400','popularitymaxvalue'=>'425','customflow'=>'3'],
['level'=>'18','stagelevel'=>'2','popularityminvalue'=>'425','popularitymaxvalue'=>'450','customflow'=>'3'],
['level'=>'19','stagelevel'=>'2','popularityminvalue'=>'450','popularitymaxvalue'=>'475','customflow'=>'3'],
['level'=>'20','stagelevel'=>'2','popularityminvalue'=>'475','popularitymaxvalue'=>'500','customflow'=>'3'],
['level'=>'21','stagelevel'=>'2','popularityminvalue'=>'500','popularitymaxvalue'=>'525','customflow'=>'3'],
['level'=>'22','stagelevel'=>'2','popularityminvalue'=>'525','popularitymaxvalue'=>'550','customflow'=>'3'],
['level'=>'23','stagelevel'=>'2','popularityminvalue'=>'550','popularitymaxvalue'=>'575','customflow'=>'3'],
['level'=>'24','stagelevel'=>'2','popularityminvalue'=>'575','popularitymaxvalue'=>'600','customflow'=>'3'],
['level'=>'25','stagelevel'=>'2','popularityminvalue'=>'600','popularitymaxvalue'=>'625','customflow'=>'3'],
['level'=>'26','stagelevel'=>'2','popularityminvalue'=>'625','popularitymaxvalue'=>'650','customflow'=>'3'],
['level'=>'27','stagelevel'=>'2','popularityminvalue'=>'650','popularitymaxvalue'=>'675','customflow'=>'3'],
['level'=>'28','stagelevel'=>'2','popularityminvalue'=>'675','popularitymaxvalue'=>'700','customflow'=>'3'],
['level'=>'29','stagelevel'=>'2','popularityminvalue'=>'700','popularitymaxvalue'=>'725','customflow'=>'3'],
['level'=>'30','stagelevel'=>'3','popularityminvalue'=>'725','popularitymaxvalue'=>'750','customflow'=>'3'],
['level'=>'31','stagelevel'=>'3','popularityminvalue'=>'750','popularitymaxvalue'=>'775','customflow'=>'3'],
['level'=>'32','stagelevel'=>'3','popularityminvalue'=>'775','popularitymaxvalue'=>'800','customflow'=>'3'],
['level'=>'33','stagelevel'=>'3','popularityminvalue'=>'800','popularitymaxvalue'=>'825','customflow'=>'3'],
['level'=>'34','stagelevel'=>'3','popularityminvalue'=>'825','popularitymaxvalue'=>'850','customflow'=>'3'],
['level'=>'35','stagelevel'=>'3','popularityminvalue'=>'850','popularitymaxvalue'=>'875','customflow'=>'3'],
['level'=>'36','stagelevel'=>'3','popularityminvalue'=>'875','popularitymaxvalue'=>'900','customflow'=>'3'],
['level'=>'37','stagelevel'=>'3','popularityminvalue'=>'900','popularitymaxvalue'=>'925','customflow'=>'3'],
['level'=>'38','stagelevel'=>'3','popularityminvalue'=>'925','popularitymaxvalue'=>'950','customflow'=>'3'],
['level'=>'39','stagelevel'=>'3','popularityminvalue'=>'950','popularitymaxvalue'=>'975','customflow'=>'3'],
['level'=>'40','stagelevel'=>'3','popularityminvalue'=>'975','popularitymaxvalue'=>'1000','customflow'=>'3'],
['level'=>'41','stagelevel'=>'3','popularityminvalue'=>'1000','popularitymaxvalue'=>'1025','customflow'=>'3'],
['level'=>'42','stagelevel'=>'3','popularityminvalue'=>'1025','popularitymaxvalue'=>'1050','customflow'=>'3'],
['level'=>'43','stagelevel'=>'3','popularityminvalue'=>'1050','popularitymaxvalue'=>'1075','customflow'=>'3'],
['level'=>'44','stagelevel'=>'3','popularityminvalue'=>'1075','popularitymaxvalue'=>'1100','customflow'=>'3'],
['level'=>'45','stagelevel'=>'3','popularityminvalue'=>'1100','popularitymaxvalue'=>'1125','customflow'=>'3'],
['level'=>'46','stagelevel'=>'3','popularityminvalue'=>'1125','popularitymaxvalue'=>'1150','customflow'=>'3'],
['level'=>'47','stagelevel'=>'3','popularityminvalue'=>'1150','popularitymaxvalue'=>'1175','customflow'=>'3'],
['level'=>'48','stagelevel'=>'3','popularityminvalue'=>'1175','popularitymaxvalue'=>'1200','customflow'=>'3'],
['level'=>'49','stagelevel'=>'3','popularityminvalue'=>'1200','popularitymaxvalue'=>'1225','customflow'=>'3'],
['level'=>'50','stagelevel'=>'4','popularityminvalue'=>'1225','popularitymaxvalue'=>'1250','customflow'=>'3'],
['level'=>'51','stagelevel'=>'4','popularityminvalue'=>'1250','popularitymaxvalue'=>'1275','customflow'=>'3'],
['level'=>'52','stagelevel'=>'4','popularityminvalue'=>'1275','popularitymaxvalue'=>'1300','customflow'=>'3'],
['level'=>'53','stagelevel'=>'4','popularityminvalue'=>'1300','popularitymaxvalue'=>'1325','customflow'=>'3'],
['level'=>'54','stagelevel'=>'4','popularityminvalue'=>'1325','popularitymaxvalue'=>'1350','customflow'=>'3'],
['level'=>'55','stagelevel'=>'4','popularityminvalue'=>'1350','popularitymaxvalue'=>'1375','customflow'=>'3'],
['level'=>'56','stagelevel'=>'4','popularityminvalue'=>'1375','popularitymaxvalue'=>'1400','customflow'=>'3'],
['level'=>'57','stagelevel'=>'4','popularityminvalue'=>'1400','popularitymaxvalue'=>'1425','customflow'=>'3'],
['level'=>'58','stagelevel'=>'4','popularityminvalue'=>'1425','popularitymaxvalue'=>'1450','customflow'=>'3'],
['level'=>'59','stagelevel'=>'4','popularityminvalue'=>'1450','popularitymaxvalue'=>'1475','customflow'=>'3'],
['level'=>'60','stagelevel'=>'4','popularityminvalue'=>'1475','popularitymaxvalue'=>'1500','customflow'=>'3'],
['level'=>'61','stagelevel'=>'4','popularityminvalue'=>'1500','popularitymaxvalue'=>'1525','customflow'=>'3'],
['level'=>'62','stagelevel'=>'4','popularityminvalue'=>'1525','popularitymaxvalue'=>'1550','customflow'=>'3'],
['level'=>'63','stagelevel'=>'4','popularityminvalue'=>'1550','popularitymaxvalue'=>'1575','customflow'=>'3'],
['level'=>'64','stagelevel'=>'4','popularityminvalue'=>'1575','popularitymaxvalue'=>'1600','customflow'=>'3'],
['level'=>'65','stagelevel'=>'4','popularityminvalue'=>'1600','popularitymaxvalue'=>'1625','customflow'=>'3'],
['level'=>'66','stagelevel'=>'4','popularityminvalue'=>'1625','popularitymaxvalue'=>'1650','customflow'=>'3'],
['level'=>'67','stagelevel'=>'4','popularityminvalue'=>'1650','popularitymaxvalue'=>'1675','customflow'=>'3'],
['level'=>'68','stagelevel'=>'4','popularityminvalue'=>'1675','popularitymaxvalue'=>'1700','customflow'=>'3'],
['level'=>'69','stagelevel'=>'4','popularityminvalue'=>'1700','popularitymaxvalue'=>'1725','customflow'=>'3'],
['level'=>'70','stagelevel'=>'4','popularityminvalue'=>'1725','popularitymaxvalue'=>'1750','customflow'=>'3'],
['level'=>'71','stagelevel'=>'4','popularityminvalue'=>'1750','popularitymaxvalue'=>'1775','customflow'=>'3'],
['level'=>'72','stagelevel'=>'4','popularityminvalue'=>'1775','popularitymaxvalue'=>'1800','customflow'=>'3'],
['level'=>'73','stagelevel'=>'4','popularityminvalue'=>'1800','popularitymaxvalue'=>'1825','customflow'=>'3'],
['level'=>'74','stagelevel'=>'4','popularityminvalue'=>'1825','popularitymaxvalue'=>'1850','customflow'=>'3'],
['level'=>'75','stagelevel'=>'4','popularityminvalue'=>'1850','popularitymaxvalue'=>'1875','customflow'=>'3'],
['level'=>'76','stagelevel'=>'4','popularityminvalue'=>'1875','popularitymaxvalue'=>'1900','customflow'=>'3'],
['level'=>'77','stagelevel'=>'4','popularityminvalue'=>'1900','popularitymaxvalue'=>'1925','customflow'=>'3'],
['level'=>'78','stagelevel'=>'4','popularityminvalue'=>'1925','popularitymaxvalue'=>'1950','customflow'=>'3'],
['level'=>'79','stagelevel'=>'4','popularityminvalue'=>'1950','popularitymaxvalue'=>'1975','customflow'=>'3'],
['level'=>'80','stagelevel'=>'4','popularityminvalue'=>'1975','popularitymaxvalue'=>'2000','customflow'=>'3'],
['level'=>'81','stagelevel'=>'4','popularityminvalue'=>'2000','popularitymaxvalue'=>'2025','customflow'=>'3'],
['level'=>'82','stagelevel'=>'4','popularityminvalue'=>'2025','popularitymaxvalue'=>'2050','customflow'=>'3'],
['level'=>'83','stagelevel'=>'4','popularityminvalue'=>'2050','popularitymaxvalue'=>'2075','customflow'=>'3'],
['level'=>'84','stagelevel'=>'4','popularityminvalue'=>'2075','popularitymaxvalue'=>'2100','customflow'=>'3'],
['level'=>'85','stagelevel'=>'4','popularityminvalue'=>'2100','popularitymaxvalue'=>'2125','customflow'=>'3'],
['level'=>'86','stagelevel'=>'4','popularityminvalue'=>'2125','popularitymaxvalue'=>'2150','customflow'=>'3'],
['level'=>'87','stagelevel'=>'4','popularityminvalue'=>'2150','popularitymaxvalue'=>'2175','customflow'=>'3'],
['level'=>'88','stagelevel'=>'4','popularityminvalue'=>'2175','popularitymaxvalue'=>'2200','customflow'=>'3'],
['level'=>'89','stagelevel'=>'4','popularityminvalue'=>'2200','popularitymaxvalue'=>'2225','customflow'=>'3'],
['level'=>'90','stagelevel'=>'4','popularityminvalue'=>'2225','popularitymaxvalue'=>'2250','customflow'=>'3'],
['level'=>'91','stagelevel'=>'4','popularityminvalue'=>'2250','popularitymaxvalue'=>'2275','customflow'=>'3'],
['level'=>'92','stagelevel'=>'5','popularityminvalue'=>'2275','popularitymaxvalue'=>'2300','customflow'=>'3'],
['level'=>'93','stagelevel'=>'5','popularityminvalue'=>'2300','popularitymaxvalue'=>'2325','customflow'=>'3'],
['level'=>'94','stagelevel'=>'5','popularityminvalue'=>'2325','popularitymaxvalue'=>'2350','customflow'=>'3'],
['level'=>'95','stagelevel'=>'5','popularityminvalue'=>'2350','popularitymaxvalue'=>'2375','customflow'=>'3'],
['level'=>'96','stagelevel'=>'5','popularityminvalue'=>'2375','popularitymaxvalue'=>'2400','customflow'=>'3'],
['level'=>'97','stagelevel'=>'5','popularityminvalue'=>'2400','popularitymaxvalue'=>'2425','customflow'=>'3'],
['level'=>'98','stagelevel'=>'5','popularityminvalue'=>'2425','popularitymaxvalue'=>'2450','customflow'=>'3'],
['level'=>'99','stagelevel'=>'5','popularityminvalue'=>'2450','popularitymaxvalue'=>'2475','customflow'=>'3'],
['level'=>'100','stagelevel'=>'5','popularityminvalue'=>'2475','popularitymaxvalue'=>'2500','customflow'=>'3']
];
}
 return self::$_data;
}
}
