<?php
namespace configdata;
/**
* gen by zeus.php
*/
class configdata_mission_setting {
const k_id = "id";
const k_type = "type";
const k_autoopen = "autoopen";
const k_openconditionid1 = "openconditionid1";
const k_openconditionvalue1 = "openconditionvalue1";
const k_openconditionid2 = "openconditionid2";
const k_openconditionvalue2 = "openconditionvalue2";
const k_isrepeat = "isrepeat";
const k_nextmissionid = "nextmissionid";
const k_completeconditionid1 = "completeconditionid1";
const k_completeconditionvalue1 = "completeconditionvalue1";
const k_completeconditionusediamond1 = "completeconditionusediamond1";
const k_completeconditionid2 = "completeconditionid2";
const k_completeconditionvalue2 = "completeconditionvalue2";
const k_completeconditionusediamond2 = "completeconditionusediamond2";
const k_completeconditionid3 = "completeconditionid3";
const k_completeconditionvalue3 = "completeconditionvalue3";
const k_completeconditionusediamond3 = "completeconditionusediamond3";
const k_awardgamecoin = "awardgamecoin";
const k_awarddiamond = "awarddiamond";
const k_awardrestaurantexp = "awardrestaurantexp";
const k_awarditemid1 = "awarditemid1";
const k_awarditemidcount1 = "awarditemidcount1";
const k_awarditemid2 = "awarditemid2";
const k_awarditemidcount2 = "awarditemidcount2";
const k_awarditemid3 = "awarditemid3";
const k_awarditemidcount3 = "awarditemidcount3";
const k_name = "name";
const k_desc = "desc";
const k_diamondfinish = "diamondfinish";
private static $_data = NULL;
public static function data() {
if (is_null ( self::$_data )) {
self::$_data = [
['id'=>'3','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'1','isrepeat'=>'0','completeconditionid1'=>'1','completeconditionvalue1'=>'501016$5','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'30','awarditemid1'=>'601001','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_1','desc'=>'MISSION_DESC_1','diamondfinish'=>'0'],
['id'=>'54','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'6','isrepeat'=>'0','completeconditionid1'=>'2','completeconditionvalue1'=>'505011$10','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'10','awarditemid1'=>'401001','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_2','desc'=>'MISSION_DESC_2','diamondfinish'=>'0'],
['id'=>'33','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'4','isrepeat'=>'0','completeconditionid1'=>'3','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'300','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'401002','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_3','desc'=>'MISSION_DESC_3','diamondfinish'=>'0'],
['id'=>'48','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'4','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'50','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'800','awarddiamond'=>'0','awardrestaurantexp'=>'40','awarditemid1'=>'401003','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_4','desc'=>'MISSION_DESC_4','diamondfinish'=>'0'],
['id'=>'28','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'5','completeconditionvalue1'=>'501011$2','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'300','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'401004','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_5','desc'=>'MISSION_DESC_5','diamondfinish'=>'0'],
['id'=>'81','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'9','isrepeat'=>'0','completeconditionid1'=>'5','completeconditionvalue1'=>'501036$10','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'1500','awarddiamond'=>'0','awardrestaurantexp'=>'80','awarditemid1'=>'401006','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_6','desc'=>'MISSION_DESC_6','diamondfinish'=>'0'],
['id'=>'30','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'7','completeconditionvalue1'=>'2$1','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'500','awarddiamond'=>'2','awardrestaurantexp'=>'30','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_7','desc'=>'MISSION_DESC_7','diamondfinish'=>'0'],
['id'=>'49','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'8','completeconditionvalue1'=>'2$15','completeconditionusediamond1'=>'15','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'1000','awarddiamond'=>'5','awardrestaurantexp'=>'30','awarditemid1'=>'209002','awarditemidcount1'=>'10','name'=>'MISSION_TITLE_8','desc'=>'MISSION_DESC_8','diamondfinish'=>'0'],
['id'=>'17','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','completeconditionid1'=>'9','completeconditionvalue1'=>'10','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'100','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'601001','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_9','desc'=>'MISSION_DESC_9','diamondfinish'=>'0'],
['id'=>'2','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'1','isrepeat'=>'0','completeconditionid1'=>'10','completeconditionvalue1'=>'301165$2','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'50','awarddiamond'=>'0','awardrestaurantexp'=>'0','name'=>'MISSION_TITLE_10','desc'=>'MISSION_DESC_10','diamondfinish'=>'0'],
['id'=>'53','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'9999','isrepeat'=>'0','completeconditionid1'=>'11','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'400','awarddiamond'=>'1','awardrestaurantexp'=>'30','name'=>'MISSION_TITLE_72','desc'=>'MISSION_DESC_72','diamondfinish'=>'0'],
['id'=>'82','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'9','isrepeat'=>'0','completeconditionid1'=>'12','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'10','name'=>'MISSION_TITLE_12','desc'=>'MISSION_DESC_12','diamondfinish'=>'0'],
['id'=>'31','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'4','isrepeat'=>'0','completeconditionid1'=>'13','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'5','awardrestaurantexp'=>'20','awarditemid1'=>'401013','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_13','desc'=>'MISSION_DESC_13','diamondfinish'=>'0'],
['id'=>'11','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','nextmissionid'=>'15','completeconditionid1'=>'14','completeconditionvalue1'=>'110001$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'100','awarddiamond'=>'0','awardrestaurantexp'=>'5','name'=>'MISSION_TITLE_14','desc'=>'MISSION_DESC_14','diamondfinish'=>'0'],
['id'=>'12','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'7$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401010','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_15','desc'=>'MISSION_DESC_15','diamondfinish'=>'0'],
['id'=>'15','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','completeconditionid1'=>'18','completeconditionvalue1'=>'110001$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'100','awarddiamond'=>'0','awardrestaurantexp'=>'5','awarditemid1'=>'401009','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_16','desc'=>'MISSION_DESC_16','diamondfinish'=>'0'],
['id'=>'32','type'=>'0','autoopen'=>'0','openconditionid1'=>'4','openconditionvalue1'=>'4','isrepeat'=>'0','completeconditionid1'=>'19','completeconditionvalue1'=>'110001$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'50','awarddiamond'=>'0','awardrestaurantexp'=>'10','awarditemid1'=>'401012','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_17','desc'=>'MISSION_DESC_17','diamondfinish'=>'0'],
['id'=>'43','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'24','completeconditionvalue1'=>'1$2','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'300','awarddiamond'=>'0','awardrestaurantexp'=>'30','name'=>'MISSION_TITLE_18','desc'=>'MISSION_DESC_18','diamondfinish'=>'0'],
['id'=>'41','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'26','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'500','awarddiamond'=>'0','awardrestaurantexp'=>'50','awarditemid1'=>'401009','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_19','desc'=>'MISSION_DESC_19','diamondfinish'=>'0'],
['id'=>'42','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'27','completeconditionvalue1'=>'3','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'30','awarditemid1'=>'401015','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_20','desc'=>'MISSION_DESC_20','diamondfinish'=>'0'],
['id'=>'341','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'4','isrepeat'=>'0','completeconditionid1'=>'30','completeconditionvalue1'=>'2','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'500','awarddiamond'=>'2','awardrestaurantexp'=>'0','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_21','desc'=>'MISSION_DESC_21','diamondfinish'=>'0'],
['id'=>'342','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'4','isrepeat'=>'0','completeconditionid1'=>'31','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'1000','awarddiamond'=>'0','awardrestaurantexp'=>'50','awarditemid1'=>'301039','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_22','desc'=>'MISSION_DESC_22','diamondfinish'=>'0'],
['id'=>'343','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'4','isrepeat'=>'0','completeconditionid1'=>'32','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'500','awarddiamond'=>'0','awardrestaurantexp'=>'20','name'=>'MISSION_TITLE_23','desc'=>'MISSION_DESC_23','diamondfinish'=>'0'],
['id'=>'45','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'42','completeconditionvalue1'=>'2','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'800','awarddiamond'=>'2','awardrestaurantexp'=>'60','name'=>'MISSION_TITLE_24','desc'=>'MISSION_DESC_24','diamondfinish'=>'0'],
['id'=>'46','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'44','completeconditionvalue1'=>'10','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'10','awardrestaurantexp'=>'80','name'=>'MISSION_TITLE_25','desc'=>'MISSION_DESC_25','diamondfinish'=>'0'],
['id'=>'25','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'45','completeconditionvalue1'=>'100','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'500','awarddiamond'=>'2','awardrestaurantexp'=>'40','name'=>'MISSION_TITLE_26','desc'=>'MISSION_DESC_26','diamondfinish'=>'0'],
['id'=>'26','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'46','completeconditionvalue1'=>'2','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'600','awarddiamond'=>'0','awardrestaurantexp'=>'60','awarditemid1'=>'401002','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_27','desc'=>'MISSION_DESC_27','diamondfinish'=>'0'],
['id'=>'35','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'4','isrepeat'=>'0','completeconditionid1'=>'47','completeconditionvalue1'=>'2','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'1000','awarddiamond'=>'0','awardrestaurantexp'=>'80','awarditemid1'=>'401004','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_28','desc'=>'MISSION_DESC_28','diamondfinish'=>'0'],
['id'=>'13','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','nextmissionid'=>'14','completeconditionid1'=>'51','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'300','awarddiamond'=>'0','awardrestaurantexp'=>'50','awarditemid1'=>'401003','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_29','desc'=>'MISSION_DESC_29','diamondfinish'=>'0'],
['id'=>'50','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'55','completeconditionvalue1'=>'1$5','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'1000','awarddiamond'=>'2','awardrestaurantexp'=>'40','name'=>'MISSION_TITLE_30','desc'=>'MISSION_DESC_30','diamondfinish'=>'0'],
['id'=>'83','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'9','isrepeat'=>'0','completeconditionid1'=>'56','completeconditionvalue1'=>'10','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'2000','awarddiamond'=>'2','awardrestaurantexp'=>'50','awarditemid1'=>'401001','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_31','desc'=>'MISSION_DESC_31','diamondfinish'=>'0'],
['id'=>'1','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'1','isrepeat'=>'0','completeconditionid1'=>'57','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'1','awardrestaurantexp'=>'20','awarditemid1'=>'401002','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_32','desc'=>'MISSION_DESC_32','diamondfinish'=>'0'],
['id'=>'34','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'4','isrepeat'=>'0','completeconditionid1'=>'58','completeconditionvalue1'=>'300','completeconditionusediamond1'=>'6','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'80','awarditemid1'=>'401009','awarditemidcount1'=>'4','name'=>'MISSION_TITLE_33','desc'=>'MISSION_DESC_33','diamondfinish'=>'0'],
['id'=>'61','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'7','isrepeat'=>'0','completeconditionid1'=>'59','completeconditionvalue1'=>'1000','completeconditionusediamond1'=>'20','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'1000','awarddiamond'=>'0','awardrestaurantexp'=>'10','awarditemid1'=>'209002','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_34','desc'=>'MISSION_DESC_34','diamondfinish'=>'0'],
['id'=>'51','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'6','isrepeat'=>'0','completeconditionid1'=>'60','completeconditionvalue1'=>'1000','completeconditionusediamond1'=>'20','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'50','awarditemid1'=>'401006','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_35','desc'=>'MISSION_DESC_35','diamondfinish'=>'0'],
['id'=>'111','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'12','isrepeat'=>'0','completeconditionid1'=>'61','completeconditionvalue1'=>'20','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'5','awardrestaurantexp'=>'30','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_36','desc'=>'MISSION_DESC_36','diamondfinish'=>'0'],
['id'=>'27','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'62','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'5','awardrestaurantexp'=>'30','awarditemid1'=>'401008','awarditemidcount1'=>'4','name'=>'MISSION_TITLE_37','desc'=>'MISSION_DESC_37','diamondfinish'=>'0'],
['id'=>'131','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'14','isrepeat'=>'0','completeconditionid1'=>'63','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'401002','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_38','desc'=>'MISSION_DESC_38','diamondfinish'=>'0'],
['id'=>'112','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'12','isrepeat'=>'0','completeconditionid1'=>'64','completeconditionvalue1'=>'100','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'401003','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_39','desc'=>'MISSION_DESC_39','diamondfinish'=>'0'],
['id'=>'71','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'8','isrepeat'=>'0','completeconditionid1'=>'65','completeconditionvalue1'=>'2','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'1000','awarddiamond'=>'2','awardrestaurantexp'=>'60','awarditemid1'=>'209002','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_40','desc'=>'MISSION_DESC_40','diamondfinish'=>'0'],
['id'=>'20','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','completeconditionid1'=>'73','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'401007','awarditemidcount1'=>'3','name'=>'MISSION_TITLE_41','desc'=>'MISSION_DESC_41','diamondfinish'=>'0'],
['id'=>'344','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'35','isrepeat'=>'0','completeconditionid1'=>'74','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'600','awarddiamond'=>'1','awardrestaurantexp'=>'20','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_42','desc'=>'MISSION_DESC_42','diamondfinish'=>'0'],
['id'=>'19','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','completeconditionid1'=>'75','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'209002','awarditemidcount1'=>'6','name'=>'MISSION_TITLE_43','desc'=>'MISSION_DESC_43','diamondfinish'=>'0'],
['id'=>'141','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'15','isrepeat'=>'0','completeconditionid1'=>'1','completeconditionvalue1'=>'505051$5','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'30','awarditemid1'=>'401006','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_44','desc'=>'MISSION_DESC_44','diamondfinish'=>'0'],
['id'=>'91','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'10','isrepeat'=>'0','completeconditionid1'=>'1','completeconditionvalue1'=>'505056$15','completeconditionusediamond1'=>'15','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'700','awarddiamond'=>'0','awardrestaurantexp'=>'40','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_45','desc'=>'MISSION_DESC_45','diamondfinish'=>'0'],
['id'=>'29','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'1','completeconditionvalue1'=>'501051$10','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'700','awarddiamond'=>'0','awardrestaurantexp'=>'40','awarditemid1'=>'401005','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_46','desc'=>'MISSION_DESC_46','diamondfinish'=>'0'],
['id'=>'171','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'18','isrepeat'=>'0','completeconditionid1'=>'2','completeconditionvalue1'=>'502006$10','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'300','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'401002','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_47','desc'=>'MISSION_DESC_47','diamondfinish'=>'0'],
['id'=>'191','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'20','isrepeat'=>'0','completeconditionid1'=>'1','completeconditionvalue1'=>'505036$6','completeconditionusediamond1'=>'6','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401003','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_48','desc'=>'MISSION_DESC_48','diamondfinish'=>'0'],
['id'=>'92','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'10','isrepeat'=>'0','completeconditionid1'=>'2','completeconditionvalue1'=>'505056$10','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'700','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'209002','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_49','desc'=>'MISSION_DESC_49','diamondfinish'=>'0'],
['id'=>'132','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'14','isrepeat'=>'0','completeconditionid1'=>'2','completeconditionvalue1'=>'505071$10','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'3','awardrestaurantexp'=>'0','awarditemid1'=>'401006','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_50','desc'=>'MISSION_DESC_50','diamondfinish'=>'0'],
['id'=>'72','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'8','isrepeat'=>'0','completeconditionid1'=>'10','completeconditionvalue1'=>'301125$2','completeconditionusediamond1'=>'1','completeconditionid2'=>'10','completeconditionvalue2'=>'301021$2','completeconditionusediamond2'=>'2','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'10','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_51','desc'=>'MISSION_DESC_51','diamondfinish'=>'0'],
['id'=>'113','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'12','isrepeat'=>'0','completeconditionid1'=>'10','completeconditionvalue1'=>'301121$1','completeconditionusediamond1'=>'1','completeconditionid2'=>'10','completeconditionvalue2'=>'301117$1','completeconditionusediamond2'=>'1','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401005','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_52','desc'=>'MISSION_DESC_52','diamondfinish'=>'0'],
['id'=>'121','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'13','isrepeat'=>'0','completeconditionid1'=>'10','completeconditionvalue1'=>'301061$2','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'1000','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'209002','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_53','desc'=>'MISSION_DESC_53','diamondfinish'=>'0'],
['id'=>'44','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'10','completeconditionvalue1'=>'301165$1','completeconditionusediamond1'=>'1','completeconditionid2'=>'10','completeconditionvalue2'=>'301037$1','completeconditionusediamond2'=>'1','completeconditionusediamond3'=>'0','awardgamecoin'=>'100','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401006','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_54','desc'=>'MISSION_DESC_54','diamondfinish'=>'0'],
['id'=>'142','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'15','isrepeat'=>'0','completeconditionid1'=>'10','completeconditionvalue1'=>'301137$5','completeconditionusediamond1'=>'5','completeconditionid2'=>'10','completeconditionvalue2'=>'301057$5','completeconditionusediamond2'=>'5','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'30','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_55','desc'=>'MISSION_DESC_55','diamondfinish'=>'0'],
['id'=>'84','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'9','isrepeat'=>'0','completeconditionid1'=>'11','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'2','completeconditionid2'=>'11','completeconditionvalue2'=>'1','completeconditionusediamond2'=>'2','completeconditionusediamond3'=>'0','awardgamecoin'=>'600','awarddiamond'=>'1','awardrestaurantexp'=>'20','awarditemid1'=>'401005','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_56','desc'=>'MISSION_DESC_56','diamondfinish'=>'0'],
['id'=>'73','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'8','isrepeat'=>'0','completeconditionid1'=>'14','completeconditionvalue1'=>'110006$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'100','awarddiamond'=>'0','awardrestaurantexp'=>'5','awarditemid1'=>'401006','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_57','desc'=>'MISSION_DESC_57','diamondfinish'=>'0'],
['id'=>'16','type'=>'0','autoopen'=>'0','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','completeconditionid1'=>'14','completeconditionvalue1'=>'113003$1','completeconditionusediamond1'=>'2','completeconditionid2'=>'14','completeconditionvalue2'=>'109002$1','completeconditionusediamond2'=>'2','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'30','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_58','desc'=>'MISSION_DESC_58','diamondfinish'=>'0'],
['id'=>'133','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'14','isrepeat'=>'0','completeconditionid1'=>'14','completeconditionvalue1'=>'105003$1','completeconditionusediamond1'=>'2','completeconditionid2'=>'14','completeconditionvalue2'=>'111002$1','completeconditionusediamond2'=>'2','completeconditionid3'=>'14','completeconditionvalue3'=>'111013$1','completeconditionusediamond3'=>'4','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401005','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_59','desc'=>'MISSION_DESC_59','diamondfinish'=>'0'],
['id'=>'52','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'6','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'6$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'10','name'=>'MISSION_TITLE_60','desc'=>'MISSION_DESC_60','diamondfinish'=>'0'],
['id'=>'14','type'=>'0','autoopen'=>'0','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'8$3','completeconditionusediamond1'=>'6','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'10','name'=>'MISSION_TITLE_61','desc'=>'MISSION_DESC_61','diamondfinish'=>'0'],
['id'=>'192','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'20','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'6$1','completeconditionusediamond1'=>'2','completeconditionid2'=>'15','completeconditionvalue2'=>'7$1','completeconditionusediamond2'=>'2','completeconditionusediamond3'=>'0','awardgamecoin'=>'100','awarddiamond'=>'0','awardrestaurantexp'=>'25','name'=>'MISSION_TITLE_62','desc'=>'MISSION_DESC_62','diamondfinish'=>'0'],
['id'=>'181','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'19','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'9$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'10','name'=>'MISSION_TITLE_63','desc'=>'MISSION_DESC_63','diamondfinish'=>'0'],
['id'=>'143','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'15','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'8$8','completeconditionusediamond1'=>'16','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401002','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_64','desc'=>'MISSION_DESC_64','diamondfinish'=>'0'],
['id'=>'161','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'17','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'8$10','completeconditionusediamond1'=>'20','completeconditionid2'=>'15','completeconditionvalue2'=>'9$1','completeconditionusediamond2'=>'2','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401004','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_65','desc'=>'MISSION_DESC_65','diamondfinish'=>'0'],
['id'=>'172','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'18','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'9$10','completeconditionusediamond1'=>'20','completeconditionid2'=>'14','completeconditionvalue2'=>'112001$1','completeconditionusediamond2'=>'2','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401003','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_66','desc'=>'MISSION_DESC_66','diamondfinish'=>'0'],
['id'=>'151','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'16','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'8$20','completeconditionusediamond1'=>'40','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'100','awarditemid1'=>'209002','awarditemidcount1'=>'5','name'=>'MISSION_TITLE_67','desc'=>'MISSION_DESC_67','diamondfinish'=>'0'],
['id'=>'47','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'5','isrepeat'=>'0','completeconditionid1'=>'51','completeconditionvalue1'=>'2','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'300','awarddiamond'=>'0','awardrestaurantexp'=>'20','awarditemid1'=>'401005','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_68','desc'=>'MISSION_DESC_68','diamondfinish'=>'0'],
['id'=>'24','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'73','completeconditionvalue1'=>'3','completeconditionusediamond1'=>'6','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'0','name'=>'MISSION_TITLE_69','desc'=>'MISSION_DESC_69','diamondfinish'=>'0'],
['id'=>'144','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'15','isrepeat'=>'0','completeconditionid1'=>'51','completeconditionvalue1'=>'2','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'401005','awarditemidcount1'=>'2','name'=>'MISSION_TITLE_70','desc'=>'MISSION_DESC_70','diamondfinish'=>'0'],
['id'=>'145','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'15','isrepeat'=>'0','completeconditionid1'=>'73','completeconditionvalue1'=>'3','completeconditionusediamond1'=>'10','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'50','name'=>'MISSION_TITLE_71','desc'=>'MISSION_DESC_71','diamondfinish'=>'0'],
['id'=>'18','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'2','isrepeat'=>'0','completeconditionid1'=>'1','completeconditionvalue1'=>'501021$5','completeconditionusediamond1'=>'5','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'10','name'=>'MISSION_TITLE_73','desc'=>'MISSION_DESC_73','diamondfinish'=>'0'],
['id'=>'22','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'14','completeconditionvalue1'=>'101001$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'150','awarddiamond'=>'0','awardrestaurantexp'=>'5','name'=>'MISSION_TITLE_74','desc'=>'MISSION_DESC_74','diamondfinish'=>'0'],
['id'=>'23','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'14','completeconditionvalue1'=>'110004$1','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'300','awarddiamond'=>'0','awardrestaurantexp'=>'10','name'=>'MISSION_TITLE_75','desc'=>'MISSION_DESC_75','diamondfinish'=>'0'],
['id'=>'21','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'3','isrepeat'=>'0','completeconditionid1'=>'15','completeconditionvalue1'=>'6$1','completeconditionusediamond1'=>'3','completeconditionid2'=>'15','completeconditionvalue2'=>'7$1','completeconditionusediamond2'=>'2','completeconditionusediamond3'=>'0','awardgamecoin'=>'200','awarddiamond'=>'0','awardrestaurantexp'=>'10','name'=>'MISSION_TITLE_76','desc'=>'MISSION_DESC_76','diamondfinish'=>'0'],
['id'=>'4','type'=>'0','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'1','isrepeat'=>'0','completeconditionid1'=>'11','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'400','awarddiamond'=>'1','awardrestaurantexp'=>'30','name'=>'MISSION_TITLE_72','desc'=>'MISSION_DESC_72','diamondfinish'=>'0'],
['id'=>'1000001','type'=>'1','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'1','isrepeat'=>'0','completeconditionid1'=>'10','completeconditionvalue1'=>'301165$2','completeconditionusediamond1'=>'2','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'0','name'=>'MISSION_TITLE_1000001','desc'=>'MISSION_DESC_1000001','diamondfinish'=>'0'],
['id'=>'1000002','type'=>'1','autoopen'=>'1','openconditionid1'=>'4','openconditionvalue1'=>'1','isrepeat'=>'0','completeconditionid1'=>'99','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'0','awardrestaurantexp'=>'0','awarditemid1'=>'111054','awarditemidcount1'=>'1','name'=>'MISSION_TITLE_1000002','desc'=>'MISSION_DESC_1000002','diamondfinish'=>'0'],
['id'=>'2000011','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'65','completeconditionvalue1'=>'7','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'150','name'=>'MISSION_TITLE_2000011','desc'=>'MISSION_DESC_2000011','diamondfinish'=>'0'],
['id'=>'2000012','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'65','completeconditionvalue1'=>'14','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'500','name'=>'MISSION_TITLE_2000012','desc'=>'MISSION_DESC_2000012','diamondfinish'=>'0'],
['id'=>'2000013','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'65','completeconditionvalue1'=>'28','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'1000','name'=>'MISSION_TITLE_2000013','desc'=>'MISSION_DESC_2000013','diamondfinish'=>'0'],
['id'=>'2000021','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'4','completeconditionvalue1'=>'12','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'20','name'=>'MISSION_TITLE_2000021','desc'=>'MISSION_DESC_2000021','diamondfinish'=>'0'],
['id'=>'2000022','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'4','completeconditionvalue1'=>'600','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'160','name'=>'MISSION_TITLE_2000022','desc'=>'MISSION_DESC_2000022','diamondfinish'=>'0'],
['id'=>'2000023','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'4','completeconditionvalue1'=>'2500','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'350','name'=>'MISSION_TITLE_2000023','desc'=>'MISSION_DESC_2000023','diamondfinish'=>'0'],
['id'=>'2000041','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'76','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'20','name'=>'MISSION_TITLE_2000041','desc'=>'MISSION_DESC_2000041','diamondfinish'=>'0'],
['id'=>'2000042','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'76','completeconditionvalue1'=>'3','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'500','name'=>'MISSION_TITLE_2000042','desc'=>'MISSION_DESC_2000042','diamondfinish'=>'0'],
['id'=>'2000043','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'76','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'1500','name'=>'MISSION_TITLE_2000043','desc'=>'MISSION_DESC_2000043','diamondfinish'=>'0'],
['id'=>'2000061','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'59','completeconditionvalue1'=>'3000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'50','name'=>'MISSION_TITLE_2000061','desc'=>'MISSION_DESC_2000061','diamondfinish'=>'0'],
['id'=>'2000062','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'59','completeconditionvalue1'=>'25000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'250','name'=>'MISSION_TITLE_2000062','desc'=>'MISSION_DESC_2000062','diamondfinish'=>'0'],
['id'=>'2000063','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'59','completeconditionvalue1'=>'100000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'600','name'=>'MISSION_TITLE_2000063','desc'=>'MISSION_DESC_2000063','diamondfinish'=>'0'],
['id'=>'2000091','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'9','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'50','name'=>'MISSION_TITLE_2000091','desc'=>'MISSION_DESC_2000091','diamondfinish'=>'0'],
['id'=>'2000092','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'9','completeconditionvalue1'=>'1500','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'250','name'=>'MISSION_TITLE_2000092','desc'=>'MISSION_DESC_2000092','diamondfinish'=>'0'],
['id'=>'2000093','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'9','completeconditionvalue1'=>'12000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'800','name'=>'MISSION_TITLE_2000093','desc'=>'MISSION_DESC_2000093','diamondfinish'=>'0'],
['id'=>'2000281','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'51','completeconditionvalue1'=>'3','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'250','name'=>'MISSION_TITLE_2000281','desc'=>'MISSION_DESC_2000281','diamondfinish'=>'0'],
['id'=>'2000282','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'51','completeconditionvalue1'=>'7','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'750','name'=>'MISSION_TITLE_2000282','desc'=>'MISSION_DESC_2000282','diamondfinish'=>'0'],
['id'=>'2000283','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'51','completeconditionvalue1'=>'17','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'2000','name'=>'MISSION_TITLE_2000283','desc'=>'MISSION_DESC_2000283','diamondfinish'=>'0'],
['id'=>'2000351','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'32','completeconditionvalue1'=>'300','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'100','name'=>'MISSION_TITLE_2000351','desc'=>'MISSION_DESC_2000351','diamondfinish'=>'0'],
['id'=>'2000352','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'32','completeconditionvalue1'=>'2000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'800','name'=>'MISSION_TITLE_2000352','desc'=>'MISSION_DESC_2000352','diamondfinish'=>'0'],
['id'=>'2000353','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'32','completeconditionvalue1'=>'3800','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'2000','name'=>'MISSION_TITLE_2000353','desc'=>'MISSION_DESC_2000353','diamondfinish'=>'0'],
['id'=>'2000361','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'64','completeconditionvalue1'=>'20','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'100','name'=>'MISSION_TITLE_2000361','desc'=>'MISSION_DESC_2000361','diamondfinish'=>'0'],
['id'=>'2000362','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'64','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'1000','name'=>'MISSION_TITLE_2000362','desc'=>'MISSION_DESC_2000362','diamondfinish'=>'0'],
['id'=>'2000363','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'64','completeconditionvalue1'=>'100','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'3000','name'=>'MISSION_TITLE_2000363','desc'=>'MISSION_DESC_2000363','diamondfinish'=>'0'],
['id'=>'2000371','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'30','completeconditionvalue1'=>'10','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'40','name'=>'MISSION_TITLE_2000371','desc'=>'MISSION_DESC_2000371','diamondfinish'=>'0'],
['id'=>'2000372','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'30','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'200','name'=>'MISSION_TITLE_2000372','desc'=>'MISSION_DESC_2000372','diamondfinish'=>'0'],
['id'=>'2000373','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'30','completeconditionvalue1'=>'500','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'800','name'=>'MISSION_TITLE_2000373','desc'=>'MISSION_DESC_2000373','diamondfinish'=>'0'],
['id'=>'2000381','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'31','completeconditionvalue1'=>'10','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'40','name'=>'MISSION_TITLE_2000381','desc'=>'MISSION_DESC_2000381','diamondfinish'=>'0'],
['id'=>'2000382','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'31','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'200','name'=>'MISSION_TITLE_2000382','desc'=>'MISSION_DESC_2000382','diamondfinish'=>'0'],
['id'=>'2000383','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'31','completeconditionvalue1'=>'500','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'800','name'=>'MISSION_TITLE_2000383','desc'=>'MISSION_DESC_2000383','diamondfinish'=>'0'],
['id'=>'2000391','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'42','completeconditionvalue1'=>'10','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'100','name'=>'MISSION_TITLE_2000391','desc'=>'MISSION_DESC_2000391','diamondfinish'=>'0'],
['id'=>'2000392','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'42','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'600','name'=>'MISSION_TITLE_2000392','desc'=>'MISSION_DESC_2000392','diamondfinish'=>'0'],
['id'=>'2000393','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'42','completeconditionvalue1'=>'500','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'1200','name'=>'MISSION_TITLE_2000393','desc'=>'MISSION_DESC_2000393','diamondfinish'=>'0'],
['id'=>'2000401','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'46','completeconditionvalue1'=>'1','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'100','name'=>'MISSION_TITLE_2000401','desc'=>'MISSION_DESC_2000401','diamondfinish'=>'0'],
['id'=>'2000402','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'46','completeconditionvalue1'=>'2','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'700','name'=>'MISSION_TITLE_2000402','desc'=>'MISSION_DESC_2000402','diamondfinish'=>'0'],
['id'=>'2000403','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'46','completeconditionvalue1'=>'3','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'1500','name'=>'MISSION_TITLE_2000403','desc'=>'MISSION_DESC_2000403','diamondfinish'=>'0'],
['id'=>'2000411','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'47','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'40','name'=>'MISSION_TITLE_2000411','desc'=>'MISSION_DESC_2000411','diamondfinish'=>'0'],
['id'=>'2000412','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'47','completeconditionvalue1'=>'20','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'200','name'=>'MISSION_TITLE_2000412','desc'=>'MISSION_DESC_2000412','diamondfinish'=>'0'],
['id'=>'2000413','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'47','completeconditionvalue1'=>'200','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'800','name'=>'MISSION_TITLE_2000413','desc'=>'MISSION_DESC_2000413','diamondfinish'=>'0'],
['id'=>'2000441','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'63','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'100','name'=>'MISSION_TITLE_2000441','desc'=>'MISSION_DESC_2000441','diamondfinish'=>'0'],
['id'=>'2000442','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'63','completeconditionvalue1'=>'200','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'600','name'=>'MISSION_TITLE_2000442','desc'=>'MISSION_DESC_2000442','diamondfinish'=>'0'],
['id'=>'2000443','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'63','completeconditionvalue1'=>'1000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'1000','name'=>'MISSION_TITLE_2000443','desc'=>'MISSION_DESC_2000443','diamondfinish'=>'0'],
['id'=>'2000451','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'62','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'100','name'=>'MISSION_TITLE_2000451','desc'=>'MISSION_DESC_2000451','diamondfinish'=>'0'],
['id'=>'2000452','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'62','completeconditionvalue1'=>'100','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'450','name'=>'MISSION_TITLE_2000452','desc'=>'MISSION_DESC_2000452','diamondfinish'=>'0'],
['id'=>'2000453','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'62','completeconditionvalue1'=>'200','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'900','name'=>'MISSION_TITLE_2000453','desc'=>'MISSION_DESC_2000453','diamondfinish'=>'0'],
['id'=>'2000461','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'75','completeconditionvalue1'=>'5','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'50','name'=>'MISSION_TITLE_2000461','desc'=>'MISSION_DESC_2000461','diamondfinish'=>'0'],
['id'=>'2000462','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'75','completeconditionvalue1'=>'15','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'150','name'=>'MISSION_TITLE_2000462','desc'=>'MISSION_DESC_2000462','diamondfinish'=>'0'],
['id'=>'2000463','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'75','completeconditionvalue1'=>'50','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'450','name'=>'MISSION_TITLE_2000463','desc'=>'MISSION_DESC_2000463','diamondfinish'=>'0'],
['id'=>'2000471','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'44','completeconditionvalue1'=>'20','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'100','name'=>'MISSION_TITLE_2000471','desc'=>'MISSION_DESC_2000471','diamondfinish'=>'0'],
['id'=>'2000472','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'44','completeconditionvalue1'=>'200','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'800','name'=>'MISSION_TITLE_2000472','desc'=>'MISSION_DESC_2000472','diamondfinish'=>'0'],
['id'=>'2000473','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'44','completeconditionvalue1'=>'2000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'1800','name'=>'MISSION_TITLE_2000473','desc'=>'MISSION_DESC_2000473','diamondfinish'=>'0'],
['id'=>'2000481','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'45','completeconditionvalue1'=>'1000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'2','awardrestaurantexp'=>'100','name'=>'MISSION_TITLE_2000481','desc'=>'MISSION_DESC_2000481','diamondfinish'=>'0'],
['id'=>'2000482','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'45','completeconditionvalue1'=>'10000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'4','awardrestaurantexp'=>'800','name'=>'MISSION_TITLE_2000482','desc'=>'MISSION_DESC_2000482','diamondfinish'=>'0'],
['id'=>'2000483','type'=>'2','autoopen'=>'1','isrepeat'=>'0','completeconditionid1'=>'45','completeconditionvalue1'=>'100000','completeconditionusediamond1'=>'0','completeconditionusediamond2'=>'0','completeconditionusediamond3'=>'0','awardgamecoin'=>'0','awarddiamond'=>'6','awardrestaurantexp'=>'1800','name'=>'MISSION_TITLE_2000483','desc'=>'MISSION_DESC_2000483','diamondfinish'=>'0']
];
}
 return self::$_data;
}
}
