<?php
namespace err;
class err_service_warehousebuildingitem_removeitembypos extends err_dbs_warehousebase_removeitem {
}
class err_service_warehousebuildingitem_upgrade extends err_dbs_warehousebuildingitem_upgrade {
}