<?php
namespace err;
class err_service_composeitem_opendiamondslot extends err_dbs_compose_item_opendiamondslot {
}
class err_service_composeitem_compose extends err_dbs_compose_item_compose {
}
class err_service_composeitem_harvestcomposeitem extends err_dbs_compose_item_harvestcomposeitem {
}