<?php
namespace err;
class err_service_mission_missioncompleteachievement extends err_dbs_mission_missioncomplete {
}
class err_service_mission_missioncomplete extends err_dbs_mission_missioncomplete {
}
class err_service_mission_missioncompleteusediamond extends err_dbs_mission_missioncompleteusediamond {
}