#数据说明:
className: traindata
DBType: dataCell
# parent: 
#TableName: chef_traindata
#数据类型
#playerDB:寄生于用户本身的数据 需要继承使用
#globalDB:全局DB 需要继承使用
#dataCell:纯数据操作单元,可独立使用
#
# - { name: albumlist, type: array, defaultValue: 2,readonly: true,comment: 用户相册 }
#name:字段名称
#type:支持数据类型 int=0 string="" array=[] bool=false
#readonly: false 默认为false ,当true的时候 setter 为 protected
#comment:为字段注释
#defaultValue:默认值
#
#更多信息见 http://redmine.cooking.com/projects/cooking/wiki/数据模板自动生成使用说明#Yaml模板说明
datas:
    - { name: status, type: int, comment: 状态, readonly: true}
    - { name: trainRoomId, type: string, comment: 培训房间ID, readonly: true}
    - { name: trainRequestId, type: string, comment: 如果发起请求,这个为请求ID, readonly: true}
    - { name: isMaster, type: bool, comment: 是否为主动发起的培训, readonly: true}
    - { name: startTime, type: int, comment: 开始时间, readonly: true}
    - { name: finishTime, type: int, comment: 完成时间, readonly: true}
    - { name: todayTrainCount, type: int, comment: 今日被培训的次数, access: 0}
    - { name: todayTrainedUserIds, type: array, comment: 今日被培训用户ID列表, access: 0}
