#数据说明:培训完成弹出的时装商店
className: trainFashionShop
DBType: dataCell
# parent: 
#TableName: chef_trainFashionShop
#数据类型
#playerDB:寄生于用户本身的数据 需要继承使用
#globalDB:全局DB 需要继承使用
#dataCell:纯数据操作单元,可独立使用
#
# - { name: albumlist, type: array, defaultValue: 2,readonly: true,comment: 用户相册 }
#name:字段名称
#type:支持数据类型 int=0 string="" array=[] bool=false
#readonly: false 默认为false ,当true的时候 setter 为 protected
#comment:为字段注释
#defaultValue:默认值
#
#更多信息见 http://redmine.cooking.com/projects/cooking/wiki/数据模板自动生成使用说明#Yaml模板说明
datas:
    - { name: id, type: string, comment: 商店ID, readonly: false}
    - { name: expiredtime, type: int, comment: 过期时间, readonly: false}
    - { name: owneruserid, type: string, comment: 赠予者的用户id, readonly: false}
    - { name: ownerchefid, type: string, comment: 赠予者的厨师id, readonly: false}
    - { name: presentuserid, type: string, comment: 被赠予者的用户id, readonly: false}
    - { name: presentchefid, type: string, comment: 被赠予者的厨师id, readonly: false}
    - { name: slotid1, type: int, comment: "位置1道具,对应31002中id", readonly: false}
    - { name: slotid2, type: int, comment: "位置2道具,对应31002中id", readonly: false}
    - { name: slotid3, type: int, comment: "位置3道具,对应31002中id", readonly: false}
