#数据说明:
className: trainservice
DBType: globalDB
# parent: 
TableName: chef_trainservices
#数据类型
#playerDB:寄生于用户本身的数据 需要继承使用
#globalDB:全局DB 需要继承使用
#dataCell:纯数据操作单元,可独立使用
#
# - { name: albumlist, type: array, defaultValue: 2,readonly: true,comment: 用户相册 }
#name:字段名称
#type:支持数据类型 int=0 string="" array=[] bool=false
#readonly: false 默认为false ,当true的时候 setter 为 protected
#comment:为字段注释
#defaultValue:默认值
#
#更多信息见 http://redmine.cooking.com/projects/cooking/wiki/数据模板自动生成使用说明#Yaml模板说明
datas:
    - { name: roomId, type: string, comment: 房间ID, readonly: false}
    - { name: masterTrainData, type: array, comment: 主人培训信息, readonly: false}
    - { name: slaveTrainData, type: array, comment: 加入者培训信息, readonly: false}
    - { name: startTime, type: int, comment: 开始时间, readonly: false}
    - { name: finishTime, type: int, comment: 完成时间, readonly: false}
    - { name: status, type: int, comment: 房间状态, readonly: false}
    - { name: joinRequests, type: array, comment: 所有加入申请, readonly: false}
    - { name: publishAdvertisement, type: bool, comment: 是否发布了广告, access: 0}
    - { name: AdvertisementId, type: string, comment: 广告ID, access: 0}
    - { name: AdvertisementExpiredTime, type: int, comment: 广告过期时间, access: 0}

